# Generated by Django 5.2.8 on 2025-11-29 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_rename_category_purchase_category_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Purchase Categories',
            },
        ),
        migrations.AlterField(
            model_name='purchase',
            name='category_text',
            field=models.CharField(blank=True, choices=[('tools', 'Outils'), ('inputs', 'Intrants'), ('other', 'Autre')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='purchases.purchasecategory'),
        ),
    ]
