# Generated by Django 5.2.7 on 2025-11-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_populate_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='ignored',
            field=models.BooleanField(default=False, help_text='Ignorer cet achat dans les totaux'),
        ),
    ]
