# Generated by Django 5.2.8 on 2025-11-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreutils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailpreference',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address for weekly reports', max_length=254, null=True),
        ),
    ]
