# Generated by Django 5.2.8 on 2025-11-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreutils', '0002_alter_emailpreference_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailpreference',
            name='last_backup_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last successful backup', null=True),
        ),
    ]
