# Generated by Django 5.2.8 on 2025-12-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreutils', '0004_usersecurity'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrostSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('season_start_year', models.IntegerField(help_text='Year the season started (e.g., 2025 for 2025-2026)')),
                ('frost_hours', models.FloatField(default=0.0, help_text='Accumulated hours < 7.5°C')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-season_start_year', 'city'],
                'unique_together': {('city', 'season_start_year')},
            },
        ),
    ]
