# Generated by Django 5.2.8 on 2025-11-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklog',
            name='hours',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
