# Generated by Django 5.2.7 on 2025-11-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_alter_worklog_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
