# Generated by Django 5.1.1 on 2026-02-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytask',
            name='is_planned_today',
            field=models.BooleanField(default=False, help_text="Sélectionnée pour aujourd'hui"),
        ),
    ]
