# Generated by Django 5.2.8 on 2025-11-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('category', models.CharField(choices=[('observation', 'Observation'), ('intervention', 'Intervention'), ('harvest', 'Récolte'), ('problem', 'Problème'), ('note', 'Note')], default='note', max_length=20)),
                ('content', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='logbook/photos/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='logbook/audio/')),
                ('tags', models.CharField(blank=True, help_text='Comma separated tags', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
