# Generated by Django 5.2.8 on 2025-12-01 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0002_remove_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#1976d2', help_text='Hex color code', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Log Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='logentry',
            name='category',
            field=models.CharField(default='note', max_length=20),
        ),
    ]
