# Generated by Django 5.2.8 on 2025-12-01 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0004_create_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='category_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='logbook.logcategory'),
        ),
    ]
