# Generated by Django 5.2.8 on 2025-12-01 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0006_migrate_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='category',
        ),
        migrations.RenameField(
            model_name='logentry',
            old_name='category_fk',
            new_name='category',
        ),
    ]
