# Generated by Django 5.2.7 on 2025-10-14 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('parcel', models.CharField(blank=True, max_length=100)),
                ('cultivation_type', models.CharField(choices=[('serre', 'Serre'), ('plein_champ', 'Plein champ')], default='plein_champ', max_length=20)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area_m2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost_per_m2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='products.product')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
