# Generated by Django 5.2.8 on 2025-11-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_populate_markets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='market_old',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
