# Generated by Django 5.2.8 on 2025-12-01 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('month', models.IntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')])),
                ('action_type', models.CharField(choices=[('plant', 'Plantation (Vert)'), ('harvest', 'Récolte (Rouge)'), ('care', 'Entretien (Jaune)')], max_length=20)),
                ('note', models.TextField(blank=True, help_text='Détails spécifiques (ex: Taille, Palissage)')),
            ],
            options={
                'ordering': ['crop_name', 'month'],
                'unique_together': {('crop_name', 'month', 'action_type')},
            },
        ),
    ]
