# Generated by Django 5.2.8 on 2025-12-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('month', models.IntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')])),
                ('treatment_type', models.CharField(choices=[('fungicide', 'Fongicide'), ('insecticide', 'Insecticide'), ('herbicide', 'Herbicide'), ('fertilizer', 'Engrais'), ('other', 'Autre')], max_length=20)),
                ('product_name', models.CharField(help_text='Nom du produit utilisé', max_length=200)),
                ('dosage', models.CharField(blank=True, help_text="Dosage ou dose d'application", max_length=100)),
                ('note', models.TextField(blank=True, help_text='Notes (cible, conditions, etc.)')),
            ],
            options={
                'verbose_name': 'Calendrier de traitement',
                'verbose_name_plural': 'Calendriers de traitement',
                'ordering': ['crop_name', 'month'],
                'unique_together': {('crop_name', 'month', 'treatment_type', 'product_name')},
            },
        ),
    ]
